### ISSUE TITLE
Overlay support

### ISSUE THREAD

**Issue by psalaets** [comichron-data/longbox#1]
Ability to show a text overlay (all markup) over the current page.

The source of the content in the overlay could be from page array prop or maybe it's part of the carousel ui.

This could be used for

- credits
- reader comments
- author comments

**Comment by cbleslie** [comment]
I think we would need to make another layer, (above page, but behind navigation, so you can still do page turns?) and that will act as a generic information layer? 

Needs discussion

**Comment by psalaets** [comment]
Sounds right to me.

I think the stacking would be (starting with closest to the person):

1. control buttons
2. nav buttons
3. overlay layer
4. page

The overlay will show arbitrary dom so we can render reader comments and author comments and whatever else. I was thinking we could use it for credits too but it seems to make more sense for that text to be in an actual page image, so the images can stand alone outside of the comic reader.

**Comment by cbleslie** [comment]
Overlay support is setup. @psalaets just need to make the spinner  trigger on load.

**Comment by psalaets** [comment]
@cbleslie what branch does the overlay stuff live in?

**Comment by cbleslie** [comment]
Master?

**Comment by psalaets** [comment]
did you push all your commits?

**Comment by cbleslie** [comment]
Maybe.  Let me check.

**Comment by cbleslie** [comment]
@psalaets Yes, it is all there. To be clear, I just wrote the component, nothing has changed since friday night. 

My bad.

**Comment by psalaets** [comment]
@cbleslie Are the new overlay files in the github repo? If so, can you link me to the files?

I can't find them here https://github.com/comichron-data/longbox/commits/master

**Comment by cbleslie** [comment]
@psalaets we good on this?

**Comment by psalaets** [comment]
yep
