### ISSUE TITLE
fullscreen mode

### ISSUE THREAD

**Issue by psalaets** [comichron-data/longbox#3]
Flip carousel or something into fullscreen mode.

https://developer.mozilla.org/en-US/docs/Web/API/Fullscreen_API

https://developer.mozilla.org/en-US/docs/Web/CSS/:fullscreen

**Comment by cbleslie** [comment]
Current work in  `feature/fullscreen` branch. Blocked because of fullscreen api not allowing scrolling.

**Comment by psalaets** [comment]
Do scrollable divs get messed up too?

**Comment by cbleslie** [comment]
To the best of my knowledge.

**Comment by psalaets** [comment]
Is this something we need to figure out before any other dev continues?

Maybe some info in https://davidwalsh.name/fullscreen

**Comment by psalaets** [comment]
@cbleslie I requested fullscreen on the root element and scrolling is working as expected in FF, chrome and safari.

In `FullscreenButton.js`

```diff
  toggleFullscreen() {
    if (this.state.isFullscreen) {
      fscreen.exitFullscreen();
      this.setState({ isFullscreen: false });
    } else {
-     fscreen.requestFullscreen(document.getElementById(this.props.fullScreenId))
+     fscreen.requestFullscreen(document.documentElement)
      this.setState({ isFullscreen: true });
    }
  }
```

**Comment by psalaets** [comment]
fwiw I tried requesting it on `#body` and `#root` and scrolling wasn't working.

**Comment by cbleslie** [comment]
We can just ship with full screen on root; for now that is.

**Comment by psalaets** [comment]
With recent changes, Carousel handles the fullscreen state and events.
