### ISSUE TITLE
basic touch events

### ISSUE THREAD

**Issue by psalaets** [comichron-data/longbox#6]
tap left goes to previous page

tap right goes to next page

tap in middle shows toolbar and page counter

no swipe support yet

**Comment by psalaets** [comment]
- https://www.html5rocks.com/en/mobile/touchandmouse/
- https://www.smashingmagazine.com/2015/03/better-browser-input-events/

**Comment by psalaets** [comment]
We're already avoiding touch delay on mobile via 

```html
<meta name="viewport" content="width=device-width">
```

**Comment by psalaets** [comment]
I've tested this on:

- macos: chrome, FF, safari
- chromeos on a convertible device: chrome (touch + mouse)
- android: chrome, ff

We're not explicitly listening for any touch events yet. Touch enabled browsers also fire click events and that's why it's working right now.

@cbleslie think we can call this good for now?

**Comment by cbleslie** [comment]
Ship it. 🚢💯
